# Generated by Django 4.1.3 on 2022-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('url', models.CharField(max_length=128)),
                ('selectors', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=64)),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('tags', models.ManyToManyField(to='news.tag')),
            ],
        ),
    ]
