# Generated by Django 4.1.3 on 2022-12-27 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('signup_location', models.CharField(blank=True, max_length=64, null=True)),
                ('signup_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('exchanges', models.ManyToManyField(to='crypto.cryptoexchange')),
                ('friends', models.ManyToManyField(to='website.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
