# Generated by Django 4.1.3 on 2022-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCalendar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('coins', models.CharField(blank=True, max_length=256, null=True)),
                ('date_event', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['date_event'],
            },
        ),
        migrations.CreateModel(
            name='EarningsCalendar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('reportDate', models.DateField(blank=True, null=True)),
                ('fiscalDateEnding', models.DateField(blank=True, null=True)),
                ('estimate', models.CharField(blank=True, max_length=16, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'ordering': ['reportDate'],
            },
        ),
        migrations.CreateModel(
            name='IPOCalendar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('exchange', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('numberOfShares', models.FloatField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('totalSharesValue', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MacroCalendar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=16, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('importance', models.CharField(blank=True, max_length=16, null=True)),
                ('event', models.CharField(blank=True, max_length=128, null=True)),
                ('actual', models.CharField(blank=True, max_length=16, null=True)),
                ('forecast', models.CharField(blank=True, max_length=16, null=True)),
                ('previous', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
