# Generated by Django 4.1 on 2022-09-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Watchlist', max_length=32)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_creator', to='website.account')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_currency', to='markets.currency')),
                ('tickers', models.ManyToManyField(blank=True, related_name='watchlist_tickers', to='markets.ticker')),
            ],
        ),
    ]
