# Generated by Django 4.1.3 on 2022-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('symbol', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('hash_algorithm', models.CharField(blank=True, max_length=64, null=True)),
                ('proof_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=16)),
                ('quote', models.CharField(max_length=16)),
                ('price', models.FloatField(null=True)),
                ('bid', models.FloatField(null=True)),
                ('ask', models.FloatField(null=True)),
                ('hourly_delta', models.FloatField(null=True)),
                ('daily_delta', models.FloatField(null=True)),
                ('weekly_delta', models.FloatField(null=True)),
                ('monthly_delta', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('base', 'quote', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CryptoExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('grade', models.CharField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'NA')], max_length=3, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('daily_vol', models.FloatField(blank=True, null=True)),
                ('monthly_vol', models.FloatField(blank=True, null=True)),
                ('countries', models.ManyToManyField(related_name='cryptoexchange_countries', to='macro.country')),
                ('currencies', models.ManyToManyField(related_name='cryptoexchange_currencies', to='markets.currency')),
                ('tickers', models.ManyToManyField(related_name='cryptoexchange_tickers', to='markets.ticker')),
            ],
        ),
    ]
